# Generated by Django 4.0 on 2021-12-16 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='entradas',
            table='entradas',
        ),
    ]
